name: 'Deploy to hosting'

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          docker run --rm \
          --volume="$PWD:/app" \
          node:16-alpine sh -c "cd /app && npm install && npm run build && npm run generate"
      - name: Done
        # uses: SamKirkland/FTP-Deploy-Action@4.3.0
        # with:
        #   server: ${{ secrets.FTP_SERVER }}
        #   username: ${{ secrets.FTP_USERNAME }}
        #   password: ${{ secrets.FTP_PASSWORD }}
        #   protocol: ftps
        #   local-dir: ./dist/
  beta:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run the tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }} # Mb7f7eIsjtmpSghx5nMlHketzhmwhgnVA8uRWXVUtc8
          NETLIFY_SITE_ID: ${{ secrets.DEV_NETLIFY_SITE_ID }} # 4ab03359-7b7c-43f4-bfe9-bd5cea92e8af
        with:
          args: deploy --dir=build --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "DEV_NETLIFY_SITE_ID"]'
